server:
  port: 5605
spring:
  application:
    name: server-driver-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.106:3306/service-driver-user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root1
    password: 987654
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml