server:
  port: 5603
spring:
  application:
    name: service-forecast-price
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/taxi-passenger?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root1
    password: 987654
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
