server:
  port: 5609

spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.106:3306/taxi-passenger?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root1
    password: 987654
  redis:
    host: 127.0.0.1
    port: 6379